### PR TITLE
fix register values over NOAA screen

### PR DESCRIPTION
**Pull request by jcalado**
Set a SCREEN_NOAA gScreenMode when entering its UI

### CODE REVIEW

**Comment by xawen** [comment]
This is better!  This stops the registers from drawing on the NOAA screen.  But two side effects:

1. The NOAA key action no longer exits the NOAA screen.  (Exit doesn't work on the NOAA screen...something else we can probably fix.)
2. After exiting the NOAA screen (with PTT) the registers do not redraw on the main screen.

I'm guessing 1 is because the exit is tied to SCREEN_MAIN some how and 2 is because gScreenMode isn't getting set back to SCREEN_MAIN when NOAA exits.

**Comment by jcalado** [comment]
Just noticed you can't also exit NOAA if the action is bound to a long press instead of short press.

**Comment by jcalado** [comment]
Fixed 1 (only the NOAA key action) and 2.

**Comment by xawen** [comment]
Looks great.  Nice work!

**Pull request merged**
